# Generated by Django 5.0.3 on 2024-03-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100, verbose_name='task')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
            ],
        ),
    ]
