# Generated by Django 5.0.3 on 2024-04-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_card_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'card'},
        ),
    ]
